### PR TITLE
Add ability to specify per-field replacements

### LINKED ISSUE #1: Importreplace not working as intended
Spotify often has `(Original Motion Picture Soundtrack)` in the album title that I was hoping to remove using this plugin. I installed the plugin and have added the following block to the config:

```
plugins: fetchart embedart convert scrub replaygain lastgenre chroma web duplicates edit plexupdate lastimport discogs acousticbrainz spotify
directory: /music
library: /config/musiclibrary.blb
pluginpath: 
    -  /usr/lib/python3.8/site-packages/beetsplug/
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no

convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1

paths:
    default: Sorted/%left{$album,1}/$album ($year)/$album ($year) - $title
    singleton: Sorted/Non-Album/$artist - $title
    comp: Sorted/Compilations/%left{$album,1}/$album ($year)/$album ($year) - $title
    albumtype_soundtrack: Sorted/%left{$album,1}/$album ($year)/$album ($year) - $title

import:
    write: yes
    copy: no
    move: no
    resume: yes
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log

embedart:
    auto: yes
    remove_art_file: yes

fetchart:
    auto: yes

replaygain:
    auto: no

importreplace:
    item_fields: title artist artist_sort artist_credit
    album_fields: album artist albumartist
    replace:
        '(Original Motion Picture Soundtrack)': ''
```
But I am still getting the `(Original Motion Picture Soundtrack)` in the album title. The plugin is installed at the path that I have included (see below):
```
ash-4.4# pwd
/usr/lib/python3.8/site-packages/beetsplug
ash-4.4# ls
absubmit.py        bench.py   convert.py     embyupdate.py   fromfilename.py  importadded.py    ipfs.py        lyrics.py        mpdstats.py     plexupdate.py  smartplaylist.py     thumbnails.py
acousticbrainz.py  bpd        deezer.py      export.py       ftintitle.py     importfeeds.py    keyfinder.py   mbcollection.py  mpdupdate.py    __pycache__    sonosupdate.py       types.py
aura.py            bpm.py     discogs.py     fetchart.py     fuzzy.py         importreplace.py  kodiupdate.py  mbsubmit.py      parentwork.py   random.py      spotify.py           unimported.py
badfiles.py        bpsync.py  duplicates.py  filefilter.py   gmusic.py        info.py           lastgenre      mbsync.py        permissions.py  replaygain.py  subsonicplaylist.py  web
bareasc.py         bucket.py  edit.py        fish.py         hook.py          __init__.py       lastimport.py  metasync         playlist.py     rewrite.py     subsonicupdate.py    zero.py
beatport.py        chroma.py  embedart.py    freedesktop.py  ihate.py         inline.py         loadext.py     missing.py       play.py         scrub.py       the.py
```

I should probably add that I am using beets using docker. Let me know if you need any other information.

### PR DESCRIPTION
**Pull request by edgars-supe**
Closes #1.

### CODE REVIEW

**Comment by edgars-supe** [comment]
@arsaboo You can try this out by installing it from the branch with
```
pip install git+git://github.com/edgars-supe/beets-importreplace.git@feature/multiple-replacements
```
Don't forget to update your configuration!

**Comment by arsaboo** [comment]
@edgars-supe I tried with the the following config, but I keep getting an error `configuration error: importreplace.item_fields not found`
```
importreplace:
  replacements:
    - item_fields: album
      album_fields: album
      replace:
        '\(Original Motion Picture Soundtrack\)': ''
        ': Original Motion Picture Soundtrack': ''
        '\(Original Motion Pictures Soundtrack\)': ''
    - item_fields: album
      album_fields: albumartist
      replace:
        ' , ': '\\\\'
        ', ': '\\\\'
        ' & ': '\\\\'
    - item_fields: album
      album_fields: genre
      replace:
        '^.*?Stage.*?Screen.*': 'Bollywood OST'
        '^.*?World.*?Country.*': 'Bollywood OST'
```

I even added, the following (with the same results)
```
    - item_fields: title
      replace:
        'THETHETHE': 'That'
```

I am guessing, there is something basic that I am missing in the config. Can you please advice...thanks!!

**Comment by edgars-supe** [comment]
Yeah, the branch version of the plugin hasn't been installed. I suspect because `setup.py` has the same version number as what you have installed. Try running
```
pip uninstall beets-importreplace
```
and then the install command.
```
pip install git+git://github.com/edgars-supe/beets-importreplace.git@feature/multiple-replacements
```

**Comment by arsaboo** [comment]
Ok...so I am not getting the error now, but I am not sure if it is working. Here's my config:

```
importreplace:
  replacements:
    - album_fields: album
      replace:
        '\(Original Motion Picture Soundtrack\)': ''
        ': Original Motion Picture Soundtrack': ''
        '\(Original Motion Pictures Soundtrack\)': ''
    - album_fields: albumartist
      replace:
        ' , ': '\\\\'
        ', ': '\\\\'
        ' & ': '\\\\'
    - album_fields: genre
      replace:
        '^.*?Stage.*?Screen.*': 'Bollywood OST'
        '^.*?World.*?Country.*': 'Bollywood OST'
```
But it is not replacing the `, ` in the album artist to `\\`
```
Correcting tags from:
    Clinton Cerejo - 3 Storeys
To:
    Clinton Cerejo, Amjad Nadeem - 3 Storeys
URL:
    https://open.spotify.com/album/4QGoInDHy9M2qrLcfY9Wpr
(Similarity: 74.0%) (tracks, artist, source, label) (Spotify, 2018, Zee Music Company)
 * Bas Tu Hai (#2)   -> Bas Tu Hai (#1) (source, index)
 * Raasleela (#3)    -> Raasleela (#2) (source, index)
 * Azaadiyaan (#1)   -> Azaadiyaan (#3) (source, index)
 * Zaroori Bewakoofi -> Zaroori Bewakoofi (source)
```
Specifically, it should have replaced it to `Clinton Cerejo\\Amjad Nadeem - 3 Storeys`

**Comment by arsaboo** [comment]
Ok looks like it should be something like:
```
importreplace:
  replacements:
    - item_fields: album
      album_fields: album
      replace:
        '\(Original Motion Picture Soundtrack\)': ''
        ': Original Motion Picture Soundtrack': ''
        '\(Original Motion Pictures Soundtrack\)': ''
    - item_fields: album
      album_fields: artist
      replace:
        ' , ': '\\\\'
        ', ': '\\\\'
        ' & ': '\\\\'
    - item_fields: album
      album_fields: genre
      replace:
        '^.*?Stage.*?Screen.*': 'Bollywood OST'
        '^.*?World.*?Country.*': 'Bollywood OST'
```

I guess, I am a little confused about `item_fields` and `album_fields`. But, I think it is working. I am testing it still and let you know if I find anything else.

**Comment by edgars-supe** [comment]
Hmm, I thought it should work with `albumartist`, but, looking at the [code](https://github.com/beetbox/beets/blob/master/beets/autotag/hooks.py) for `AlbumInfo`, it looks like in the import process the object has `artist`, not `albumartist`. However, the database class has `albumartist`, not `artist`. Quite confusing. I'll have to edit the readme.
Glad to hear it appears to be working finally!

Some ideas:
1) You can simplify the first replacement by writing `\(Original Motion Picture[s]? Soundtrack\)`. `[s]?` matches zero or one `s` character, so you can catch both cases with one regex. 
2) Similarly, in the second one, `[\s]?, ` to match the optional space before the comma. You can also use `*` instead of `?` to match zero or more spaces.

**Comment by arsaboo** [comment]
So, here's another weird issue (and this may be due to the fields being incorrectly labeled). Here's my config:

```
importreplace:
  replacements:
    - item_fields: album
      album_fields: album
      replace:
        '\(Original Motion Picture[s]? Soundtrack\)': ''
        ': Original Motion Picture Soundtrack': ''
    - item_fields: album
      album_fields: artist
      replace:
        ' , ': '\\\\'
        ', ': '\\\\'
        ' & ': '\\\\'
    - item_fields: album
      album_fields: genre
      replace:
        '^.*?Stage.*?Screen.*': 'Bollywood OST'
        '^.*?World.*?Country.*': 'Bollywood OST'
```

Now, I was hoping that the `', '` replacement would only work for album artist, but it seems it is also replacing album title. Any thoughts, what the fields should be?

```
Correcting tags from:
    Aah Chak 2018, Pt. 1
To:
    Aah Chak 2018\\Pt. 1
URL:
    https://open.spotify.com/album/6dFqOqhkFkNLhg1VV3vab1
(Similarity: 82.5%) (tracks, source) (Spotify, 2017, Ishtar Music Pvt. Ltd.)
```

I agree, we need to clarify these things in the readme. We can use some of these advanced examples in the config.

**Comment by edgars-supe** [comment]
Hi! Sorry for the delay.
I haven't been able to find any reason why it's not working correctly. I looked at my tests and noticed some strange behavior, which I've fixed in the latest commit, however. On the off-chance that it is relevant to your issue, try uninstalling and installing the plugin to see if that replacement works as expected.

Also, could you also try it out on an album that is on MusicBrainz? Ideally it would be the same album (you can specify the source to use when importing with `--search-id <MB release ID or URL, Spotify URL (probably works?)>`). Perhaps it's an issue with the Spotify plugin, though I didn't notice anything suspicious there either.

Lastly, `TrackInfo` (the objects that `item_fields` replacements are run on) doesn't have an `album` field. And, at least according to the tests, having it there doesn't "leak" into replacing it on `AlbumInfo`.

**Comment by arsaboo** [comment]
So, I updated the plugin and now it is not replacing the `(Original Motion Picture Soundtrack)` in `album`. I am assuming the config has to be updated `item_fields` or the `album_fields` part, but I am a little confused. 

```
/mnt/music/Hindi Music/H/Ha Ha Hee Hee Hoo Hoo (1955) (6 items)
Correcting tags from:
    Vinod - Ha Ha Hee Hee Hoo Hoo
To:
    Vinod - Ha Ha Hee Hee Hoo Hoo (Original Motion Picture Soundtrack)
URL:
    https://open.spotify.com/album/6ifRnY46ftoDBIdHbIXBvO
```

Here's my config:
```
importreplace:
  replacements:
    - item_fields: album
      album_fields: album
      replace:
        '\(Original Motion Picture[s]? Soundtrack\)': ''
        ': Original Motion Picture Soundtrack': ''
    - item_fields: album
      album_fields: artist
      replace:
        ' , ': '\\\\'
        ', ': '\\\\'
        ' & ': '\\\\'
    - item_fields: album
      album_fields: genre
      replace:
        '^.*?Stage.*?Screen.*': 'Bollywood OST'
        '^.*?World.*?Country.*': 'Bollywood OST'
```

I am trying to remove `(Original Motion Picture Soundtrack)` from the album title; use `\\` as the separator for albumartist; and replace the genre to `Bollywood OST`. Quite possible that the above config is not quite right.

**Comment by arsaboo** [comment]
I tried removing `item_fields`, but it still does not work. Could you please advise how the config should look?

```
importreplace:
  replacements:
    # this should only work on albumtitle
    - album_fields: album
      replace:
        '\(Original Motion Picture[s]? Soundtrack\)': ''
        ': Original Motion Picture Soundtrack': ''
    # this should only work on albumartist
    - album_fields: artist
      replace:
        ' , ': '\\\\'
        ', ': '\\\\'
        ' & ': '\\\\'
    # this should only work on genre
    - album_fields: genre
      replace:
        '^.*?Stage.*?Screen.*': 'Bollywood OST'
        '^.*?World.*?Country.*': 'Bollywood OST'
```

**Comment by edgars-supe** [comment]
Sorry about that, looks like my changes had introduced a bug. Noticed a strange difference when running in beets as opposed to tests in the IDE, which broke the whole thing and slowed my PC to a crawl.

The config in your last comment looks okay. I tried checking it on importing from Spotify, but for some reason it doesn't want to match my albums to anything on Spotify. Can you try it on your end again, please? Uninstall and install the plugin, of course.

**Comment by arsaboo** [comment]
I think it is working now. I will test some more, but it is already promising :)

**Comment by arsaboo** [comment]
It is working now and I think you can merge this PR.

**Comment by edgars-supe** [comment]
Awesome, glad to hear that! Thanks for all the help! :)

**Pull request merged**
